export const HOME = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const ADD_IDEA = '/add-idea'
export const SHOW_IDEA_BASE = '/show'
export const SHOW_IDEA = '/show/:id'
